<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Resultados</name>
   <tag></tag>
   <elementGuidId>2aa114e3-5b7f-41f7-ae08-57480391b8b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#result-stats</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='result-stats']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ae181cab-34ee-414a-b080-038c081d4d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>result-stats</value>
      <webElementGuid>865ec912-4921-4e63-8e0a-4fdfbce0cc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cerca de 2.270.000.000 resultados (0,38 segundos) </value>
      <webElementGuid>7aeafdab-700f-4225-99df-1645fe827ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result-stats&quot;)</value>
      <webElementGuid>644a6fea-ee32-4574-9185-2895021d9d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='result-stats']</value>
      <webElementGuid>237e43b8-e2fe-4692-ba2a-e31d5a6617a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slim_appbar']/div/div</value>
      <webElementGuid>c3d661aa-7741-4c93-b273-ac7750ad8e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verbatim'])[1]/following::div[8]</value>
      <webElementGuid>15ca28bc-934c-4393-8c55-436cf3e78aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todos los resultados'])[2]/following::div[9]</value>
      <webElementGuid>ed95a9e4-2118-4227-88ee-450f5478f801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuración rápida'])[1]/preceding::div[1]</value>
      <webElementGuid>be27b030-7f48-4168-8d67-7ec50d1820ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cerca de 2.270.000.000 resultados']/parent::*</value>
      <webElementGuid>4d81e66a-39c8-4769-a65f-80e3ba3b0879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]/div/div/div/div/div</value>
      <webElementGuid>9d032168-34a6-4fec-807c-f6823e439006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'result-stats' and (text() = 'Cerca de 2.270.000.000 resultados (0,38 segundos) ' or . = 'Cerca de 2.270.000.000 resultados (0,38 segundos) ')]</value>
      <webElementGuid>45fccddd-44be-4f54-8d31-722502795833</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
